# Travis CI script

language: c

cache: ccache

sudo: required

addons:
  apt:
    packages:
    - uuid-dev

env:
#- BUILD_TYPE=default ZMQ_REPO=zeromq2-x
- BUILD_TYPE=default ZMQ_REPO=zeromq3-x
- BUILD_TYPE=default ZMQ_REPO=zeromq4-x WITH_LIBSODIUM=1
- BUILD_TYPE=default ZMQ_REPO=libzmq    WITH_LIBSODIUM=1
#- BUILD_TYPE=valgrind ZMQ_REPO=zeromq2-x
- BUILD_TYPE=valgrind ZMQ_REPO=zeromq3-x
- BUILD_TYPE=valgrind ZMQ_REPO=zeromq4-x WITH_LIBSODIUM=1
- BUILD_TYPE=valgrind ZMQ_REPO=libzmq    WITH_LIBSODIUM=1
#- BUILD_TYPE=qt-android
#- BUILD_TYPE=check-py

before_script:
#- sudo apt-get install uuid-dev
- ./autogen.sh

# Build and check this project according to the BUILD_TYPE
script: travis_wait 30 ./ci_build.sh
